"""add follow_ups to turns

Revision ID: ab7889016e0c
Revises: 01b51fa89f39
Create Date: 2026-07-21 21:20:10.256260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7889016e0c'
down_revision: Union[str, None] = '01b51fa89f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('follow_ups', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_turns', 'follow_ups')
    # ### end Alembic commands ###
